site_name: Sematext Documentation
site_url: https://sematext.com/docs
strict: true
pages:
    - Getting Started: index.md
    - User Guide:
      - Logs Guide: guide/logs-guide.md
      - Monitoring Guide: guide/monitoring-guide.md
      - Dashboards Guide: guide/dashboards-guide.md
      - Alerts and Events Guide: guide/alerts-and-events-guide.md
    - Logs:
      - Overview: logs/index.md
      - Sending Log Events:
        - Overview: logs/sending-log-events.md
        - Using Elasticsearch API: logs/index-events-via-elasticsearch-api.md
        - Logstash: logs/logstash.md
        - Syslog:
          - Overview: logs/syslog.md
          - JSON Messages over Syslog: logs/json-messages-over-syslog.md
          - rsyslog: logs/rsyslog.md
          - syslogd: logs/syslogd.md
          - syslog-ng: logs/syslog-ng.md
          - Authorizing IPs for Syslog: logs/authorizing-ips-for-syslog.md
        - JSON: logs/json.md
      - Searching Log Events:
        - Overview: logs/searching-log-events.md
        - Logsene CLI: logs/logsene-cli.md
        - Search Syntax: logs/search-syntax.md
        - Using Elasticsearch API: logs/search-through-the-elasticsearch-api.md
        - Kibana: logs/kibana.md
      - Field Types: logs/field-types.md
      - Supported Date Formats: logs/supported-date-formats.md
      - Special Fields: logs/special-fields.md
      - Changelog: logs/changelog.md
      - FAQ: logs/faq.md
    - Monitoring:
      - Overview: monitoring/index.md
      - Java Agent:
        - Overview:  monitoring/spm-client.md
        - Embedded Mode: monitoring/spm-monitor-javaagent.md
        - Standalone Mode: monitoring/spm-monitor-standalone.md
        - Switching Modes: monitoring/spm-monitor-switching-modes.md
        - Chef Recipe: monitoring/chef-recipe.md
      - Node Agent: monitoring/node-agent.md
      - Docker Agent: sematext-docker-agent/index.md
      - Network Map: monitoring/network-map.md
      - On Demand Profiling: monitoring/on-demand-profiling.md
      - Custom Metrics: monitoring/custom-metrics.md
      - Tags: monitoring/tag-support.md
      - Coda Hale Metrics Reporter: monitoring/coda-hale-metrics-reporter.md
      - Changelog: monitoring/changelog.md
      - FAQ: monitoring/spm-faq.md
    - Tracing:
      - Overview: tracing/index.md
      - Enabling: tracing/enable.md
      - Tracing Database Calls: tracing/database-operations.md
      - Supported Tech: tracing/supported-technologies.md
      - Custom Pointcuts: tracing/custom-pointcuts.md
      - Transaction Naming: tracing/transaction-naming.md
      - Tracing Scala: tracing/scala.md
    - Alerts:
      - Overview: alerts/index.md
      - Account Default Hooks: alerts/account-default-hooks.md
    - Events:
      - Overview: events/index.md
    - Integrations:
      - Overview: integration/index.md
      - Monitoring Akka: integration/akka.md
      - Monitoring Apache: integration/apache.md
      - Monitoring AWS: integration/aws.md
      - Monitoring Cassandra: integration/cassandra.md
      - Monitoring ClickHouse: integration/clickhouse.md
      - Monitoring Docker: integration/docker.md
      - Monitoring Elasticsearch: integration/elasticsearch.md
      - Monitoring Hadoop: integration/hadoop.md
      - Monitoring HAProxy: integration/haproxy.md
      - Monitoring HBase: integration/hbase.md
      - Monitoring JVM: integration/jvm.md
      - Monitoring Kafka: integration/kafka.md
      - Monitoring MySQL: integration/mysql.md
      - Monitoring MongoDB: integration/mongodb.md
      - Monitoring Nginx: integration/nginx.md
      - Monitoring Nginx Plus: integration/nginxplus.md
      - Monitoring Node.js: integration/node.js.md
      - Monitoring PHP: integration/php.md
      - Monitoring Redis: integration/redis.md
      - Monitoring Sensei: integration/sensei.md
      - Monitoring Solr: integration/solr.md
      - Monitoring SolrCloud: integration/solrcloud.md
      - Monitoring Spark: integration/spark.md
      - Monitoring Storm: integration/storm.md
      - Monitoring Tomcat: integration/tomcat.md
      - Monitoring ZooKeeper: integration/zookeeper.md
      - Big Panda: integration/alerts-bigpanda-integration.md
      - Custom Webhooks: integration/alerts-webhooks-integration.md
      - Email: integration/alerts-email-integration.md
      - HipChat: integration/alerts-hipchat-integration.md
      - Nagios: integration/alerts-nagios-integration.md
      - OpsGenie: integration/alerts-opsgenie-integration.md
      - PagerDuty: integration/alerts-pagerduty-integration.md
      - Pushover: integration/alerts-pushover-integration.md
      - Slack: integration/alerts-slack-integration.md
      - VictorOps: integration/alerts-victorops-integration.md
      - Zapier: integration/alerts-zapier-integration.md
    - Sematext Enterprise:
      - Overview: sematext-enterprise/index.md
      - Licensing: sematext-enterprise/licensing.md
      - On-premises vs SaaS: sematext-enterprise/on-premises-vs-saas.md
      - FAQ: sematext-enterprise/faq.md
    - Sematext Docker Agent:
      - Overview: sematext-docker-agent/index.md
      - Installation: sematext-docker-agent/installation.md
      - Configuration: sematext-docker-agent/configuration.md
      - Troubleshooting: sematext-docker-agent/troubleshooting.md
      - FAQ: sematext-docker-agent/faq.md
    - Logagent:
      - Overview: logagent/index.md
      - Installation:
        - Docker: logagent/installation-docker.md
        - Linux & Mac OS X: logagent/installation.md
        - Windows: logagent/installation-windows.md
        - Heroku: logagent/installation-heroku.md
      - Usage:
        - Command Line Parameters: logagent/cli-parameters.md
        - Configuration: logagent/config-file.md
        - Log Parser Patterns: logagent/parser.md
      - Plugins:
        - Overview: logagent/plugins.md
        - Input Filter:
          - About filters: logagent/filters.md
          - Grep input filter: logagent/input-filter-grep.md
          - Grok input filter: logagent/input-filter-grok.md
        - Input Plugins:
          - Standard input: logagent/input-plugin-stdin.md
          - File input: logagent/input-plugin-files.md
          - Docker logs input: logagent/input-plugin-dockerlogs.md
          - Syslog input: logagent/input-plugin-syslog.md
          - Apache Kafka input: logagent/input-plugin-kafka.md
          - InfluxDB input: logagent/input-plugin-influxdb-http.md
          - TCP input: logagent/input-plugin-tcp.md
          - MQTT client input: logagent/input-plugin-mqtt-client.md
          - MQTT broker input: logagent/input-plugin-mqtt-broker.md
          - GELF input: logagent/input-plugin-gelf.md
          - Command input: logagent/input-plugin-command.md
          - Elasticsearch HTTP: logagent/input-plugin-elasticsearch-http.md
          - Elasticsearch query: logagent/input-plugin-elasticsearch-query.md
          - MSSQL query: logagent/input-plugin-mssql.md
          - MySql query: logagent/input-plugin-mysql.md
          - Cassandra query: logagent/input-plugin-cassandra.md
          - ZeroMQ input: logagent/input-plugin-zeromq.md
          - Postgresql query: logagent/input-plugin-postgresql.md
          - Apple device location: logagent/logagent-apple-location.md
          - Nova dust sensor: logagent/logagent-novasds.md
          - Cloud Foundry input: logagent/input-plugin-cloudfoundry.md
        - Output Filter:
          - Access Watch output filter: logagent/output-filter-accesswatch.md
          - SQL output filter: logagent/output-filter-sql.md
          - AES encrypt fields: logagent/output-filter-aesencryptfields.md
          - Hash fields: logagent/output-filter-hashfields.md
          - Remove fields: logagent/output-filter-removefields.md
          - IP truncate fields: logagent/output-filter-iptruncatefields.md
          - Docker enrichment: logagent/output-filter-dockerenrichment.md
        - Output Plugins:
          - Standard output: logagent/output-plugin-stdout.md
          - GELF: logagent/output-plugin-gelf.md
          - MQTT: logagent/output-plugin-mqtt.md
          - Files: logagent/output-plugin-files.md
          - Elasticsearch: logagent/output-elasticsearch.md
          - Amazon Elasticsearch: logagent/output-plugin-aws-elasticsearch.md
          - InfluxDB: logagent/output-plugin-influxdb.md
          - Apache Kafka: logagent/output-plugin-kafka.md
          - ZeroMQ: logagent/output-plugin-zeromq.md
          - rTail: logagent/output-plugin-rtail.md
          - Slack Webhook: logagent/output-plugin-slack.md
          - Prometheus Alertmanager: logagent/output-plugin-prometheus-alertmanager.md
      - How-To:
          - GDPR personal data in web server logs: logagent/how-to-gdpr_web_logs.md
          - IDE Integration and debugging: logagent/logagent-ide-conf.md
      - FAQ: logagent/faq.md
    - API: api/index.md
    - FAQ: faq.md


theme:
  name: material
  custom_dir: 'mkdocs-material-custom'
repo_url: https://github.com/sematext/docs/
edit_uri: edit/master/docs/
# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  font:
    text: 'Roboto,sans-serif'
  social:
    - type: 'github'
      link: 'https://github.com/sematext'
    - type: 'twitter'
      link: 'https://twitter.com/sematext'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/sematext-international-llc'
    - type: 'facebook'
      link: 'https://www.facebook.com/Sematext'
    - type: 'google-plus'
      link: 'https://plus.google.com/+SematextGroup'
    - type: 'slideshare'
      link: 'https://www.slideshare.net/sematext'
    - type: 'feed'
      link: 'http://feeds.feedburner.com/SematextBlog'

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/code-tabs.css'

extra_javascript:
  - 'javascripts/extra.js'

markdown_extensions:
  - toc(permalink=true)
  - codehilite
  - meta
  - admonition
  - pymdownx.superfences:
# upgrade to pymdownx 4.10... first      preserve_tabs: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
