name: Puppeteer scripts  sync
run-name: ${{ github.actor }} is syncing puppeteer example scripts
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'docs/synthetics/scriptExamples.js'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes scriptExamples.js to the repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SEMATEXT_CLOUD_TOKEN }}
        with:
          source_file: 'docs/synthetics/scriptExamples.js'
          destination_repo: 'sematext/sematext-cloud'
          destination_branch: 'master'
          user_email: 'build@sematext.com'
          user_name: 'build-sematext'
          commit_message: 'syncing scriptExamples.js'